# Permalinks
permalink:           pretty

# Setup
title:               'Software developer'
url:                 https://alex-alekseichuk.github.io
tagline:             The personal blog of software developer Alex Alekseichuk
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             "https://alex-alekseichuk.github.io"

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alex Alekseichuk
  url:               https://alex-alekseichuk.github.io
  email:             alex.alekseichuk@yandex.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/alex-alekseichuk/alex-alekseichuk.github.io

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
